### ISSUE TITLE
Does this work with Node v12 LTS and HTTP/2?

### ISSUE THREAD

**Issue by niftylettuce** [cusspvz/proxywrap#30]

**Comment by cusspvz** [comment]
Hey @niftylettuce !

I believe the PROXY protocol standards for HTTP 1.X apply the same way for HTTP 2.X. Although, there are two versions of the proxy protocol and this only covers the version 1.

If you feel like you want to contribute to this, feel free to add support to it.

**Comment by niftylettuce** [comment]
Any chance I could tip/sponsor you for adding/testing HTTP/2 and optionally if you had the time; PROXY v2?  Toss me an email if so, niftylettuce@gmail.com

**Comment by niftylettuce** [comment]
This doesn't work with HTTP/2 right now because `http2` doesn't export a `Server` property like `http` does, and therefore it doesn't inherit anything and throws this error:

```sh
util.js:157
    throw new ERR_INVALID_ARG_TYPE('superCtor', 'Function', superCtor);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor" argument must be of type function. Received undefined
    at Object.inherits (util.js:157:11)
    at Object.exports.proxy (/Users/user/Projects/project/node_modules/findhit-proxywrap/lib/proxywrap.js:148:8)
```
